import Player from "@/components/cards/mmd/Player";
import Loading from "@/components/common/Loading";
import LatestArticles from "@/components/home/LatestArticles";
import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";
import { AiOutlineArrowDown } from "react-icons/ai";
import { FaInstagram } from "react-icons/fa6";

export const metadata: Metadata = {
  title: "ホーム",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <div className="w-full h-dvh">
        <Player />
        <div className="absolute inset-0 flex items-end justify-end p-6">
          <div className="'backdrop-blur-md rounded-md bg-white/60 p-6 flex flex-col gap-6 border items-center justify-center">
            <div className="flex items-center justify-center gap-3">
              <Link href="https://instagram.com/mashiro_voc" target="_blank">
                <Button variant="outline">
                  <FaInstagram size={20} />
                </Button>
              </Link>
              <Link href="#ltsArticles" scroll={true}>
                <Button variant="default">最新記事を読む</Button>
              </Link>
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 right-0 flex justify-center p-3">
          <Link href="#mainSection" scroll={true}>
            <div className="p-3 rounded-full bg-black/60 text-white border">
              <AiOutlineArrowDown />
            </div>
          </Link>
        </div>
      </div>
      <div id="mainSection" className="max-w-[1280px] mx-auto">
        <div className="p-3 space-y-6">
          <div className="space-y-3">
            <div id="ltsArticles" className="flex justify-between items-center">
              <div className="text-lg font-bold flex items-center">
                最新の記事
              </div>
            </div>
            <div className="divide-y">
              <Suspense fallback={<Loading />}>
                <LatestArticles />
              </Suspense>
            </div>
            <Link href="/articles/all" className="block">
              <Button variant="outline">もっと見る</Button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

export default page;
