import { ThemeProvider } from "@/libs/ThemeProvider";
import { cn } from "@/libs/utils";
import type { Metadata } from "next";
import { Hachi_Maru_Pop } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const hachiMaruPop = Hachi_Maru_Pop({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "400",
});

export const metadata: Metadata = {
  title: {
    template: "%s / ましろさんブログ",
    default: "ましろさんブログ",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          hachiMaruPop.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster position="top-left" />
      </body>
    </html>
  );
}
